AWSTemplateFormatVersion: '2010-09-09'
Description: 'A.'
Parameters:
  DBName:
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
    Default: wordpressdb
    Description: The WordPress database name
    Type: List<AWS::EC2::AvailabilityZone::Name>
Mappings:
Resources:
Outputs: